export const ENV_CONFIG_FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY as string;
export const ENV_CONFIG_FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN as string;
export const ENV_CONFIG_FIREBASE_PROJECT_ID = process.env.REACT_APP_FIREBASE_PROJECT_ID as string;
export const ENV_CONFIG_FIREBASE_STORAGE_BUCKET = process.env.REACT_APP_FIREBASE_STORAGE_BUCKET as string;
export const ENV_CONFIG_FIREBASE_MESSAGING_SENDER_ID = process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID as string;
export const ENV_CONFIG_FIREBASE_APP_ID = process.env.REACT_APP_FIREBASE_APP_ID as string;
export const ENV_CONFIG_FIREBASE_MEASUREMENT_ID = process.env.REACT_APP_FIREBASE_MEASUREMENT_ID as string;
